[tool.poetry]
name = "d-z-13-1"
version = "0.1.0"
description = ""
authors = ["Eduard Meister <eduard.meister@me.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^8.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
